datasource:
  mysql:
    url: jdbc:mysql://192.168.161.70:3306/dujunhui?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  sqlserver:
    url: jdbc:jtds:sqlserver://192.168.161.70:1433;databaseName=dishaws20181010
    username: sa
    password: dsyyjtwjs00
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    validation-query: select 1
  sqlserver2:
    url: jdbc:jtds:sqlserver://192.168.161.70:1433;databaseName=dishaws20190226
    username: sa
    password: dsyyjtwjs00
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    validation-query: select 1

server:
  port: 8880
  servlet:
    session:
      timeout: 6000  # session过期时间 如果没有指定持续时间后缀，则使用秒。 如： 24h 表示24小时


#图片上传的位置
file:
  localUploadPath: C:\\webSite\\DUJUNHUI_vue\\

spring:
  jta:
    atomikos:
      properties:
        max-actives: 50
        max-timeout: 300000
        default-jta-timeout: 10000
        enable-logging: true
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host: 127.0.0.1        # Redis服务器连接地址
    port: 6379             # Redis服务器连接端口
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  session:
    store-type: redis              # 使用redis存储session
    redis:
      namespace: spring:session    # 用于存储会话的键的名称空间。 sping文件夹下的session文件夹


mybatis:
  configuration:
    cache-enabled: true            #开启二级缓存


key:
  sysuserkey: admin                # redis中存储后台登录用户的key前缀
